---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build release
        run: cargo build --verbose --release

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: esp-create-project-${{ matrix.config.os }}
          asset_path: target/release/esp-create-project
          asset_content_type: application/octet-stream