---
name: "tagged-release windows"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build release
        run: cargo build --verbose --release

      - name: Rename release build
        run: mv target/release/esp-create-project.exe esp-create-project-windows-x86_64.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: esp-create-project-windows-x86_64.exe